name: audio_cast
description: A package for casting audio to streaming devices such as Hi-Fi systems and streaming sticks, written in pure Dart.
version: 0.0.1+1
homepage: https://www.peterscode.dev
repository: https://github.com/peterscodee/audio_cast

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  state_notifier: ^0.6.0

  http: ^0.13.3
  http_server: ^1.0.0
  mp3_info: ^0.2.0
  # upnp: ^2.0.1
  dart_chromecast: ^0.2.5
  multicast_dns: ^0.3.1
  xml: ^5.2.0
  file: '>=5.0.0 <6.0.0'
  js: ^0.6.3
  #upnp:
  #  git: https://github.com/peterscodee/upnp_dart.git

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.14.4
